Vagrant.configure(2) do |config|
  # create the master node
 config.vm.define "master" do |master|
   master.vm.box = "ubuntu/jammy64"
   master.vm.hostname = "Master"
   master.vm.network "private_network", ip: "192.168.57.10"
   master.vm.boot_timeout = 900
   master.vm.provision "shell", path: "lampstack_install.sh"
   master.vm.provision "shell", path: "apache_setup.sh"
 end

   
 # create the slave node
 config.vm.define "slave" do |slave|
   slave.vm.box = "ubuntu/jammy64"
   slave.vm.hostname = "Slave"
   slave.vm.network "private_network", ip: "192.168.57.12"
   slave.vm.boot_timeout = 900
 end
end
